language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - SYMFONY_VERSION=^3.4
  - SYMFONY_VERSION=^4.3

cache:
  directories:
    - $COMPOSER_CACHE_DIR

matrix:
  allow_failures: []
  exclude: []

before_script:
  - if [ "$SYMFONY_VERSION" = "^4.0" ]; then composer config minimum-stability dev; composer config prefer-stable true; fi
  - travis_wait composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source
  - travis_wait composer install --dev --prefer-source

script: ./vendor/bin/simple-phpunit

notifications:
  email:
    - system@kibatic.com
